language: node_js
os: linux
node_js:
  - "14"
jobs:
  include:
    - stage: testing
      if: branch in (main)
      install: npm install
      script: # if this is not set, it will run npm run test
        - npm install codecov -g
        - npm run test
      after_success:
        - codecov
    - stage: npm release
      # only release on master branch
      if: branch = main
      install: npm install
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: true
        on:
          all_branches: true
